export const SUBURB_TO_LOCAL_BOARD: Record<string, string> = {
  "Albert-Eden": "Albert-Eden Local Board",
  "Balmoral": "Albert-Eden Local Board",
  "Epsom": "Albert-Eden Local Board",
  "Greenlane": "Albert-Eden Local Board",
  "Greenwoods Corner": "Albert-Eden Local Board",
  "Kingsland": "Albert-Eden Local Board",
  "Morningside": "Albert-Eden Local Board",
  "Mount Albert": "Albert-Eden Local Board",
  "Mount Eden": "Albert-Eden Local Board",
  "New Windsor": "Albert-Eden Local Board",
  "Owairaka": "Albert-Eden Local Board",
  "Point Chevalier": "Albert-Eden Local Board",
  "Sandringham": "Albert-Eden Local Board",
  "St Lukes": "Albert-Eden Local Board",
  "Waterview": "Albert-Eden Local Board",
  "Western Springs": "Albert-Eden Local Board",

  "Devonport": "Devonport-Takapuna Local Board",
  "Belmont": "Devonport-Takapuna Local Board",
  "Bayswater": "Devonport-Takapuna Local Board",
  "Cheltenham": "Devonport-Takapuna Local Board",
  "Hauraki": "Devonport-Takapuna Local Board",
  "Narrow Neck": "Devonport-Takapuna Local Board",
  "Stanley Bay": "Devonport-Takapuna Local Board",
  "Takapuna": "Devonport-Takapuna Local Board",
  "Castor Bay": "Devonport-Takapuna Local Board",
  "Campbells Bay": "Devonport-Takapuna Local Board",
  "Milford": "Devonport-Takapuna Local Board",
  "Sunnynook": "Devonport-Takapuna Local Board",
  "Forrest Hill": "Devonport-Takapuna Local Board",

  "Albany": "Upper Harbour Local Board",
  "Greenhithe": "Upper Harbour Local Board",
  "Herald Island": "Upper Harbour Local Board",
  "Hobsonville": "Upper Harbour Local Board",
  "Paremoremo": "Upper Harbour Local Board",
  "Schnapper Rock": "Upper Harbour Local Board",
  "Unsworth Heights": "Upper Harbour Local Board",
  "West Harbour": "Upper Harbour Local Board",
  "Whenuapai": "Upper Harbour Local Board",
  "Luckens Point": "Upper Harbour Local Board",
  "Scott Point": "Upper Harbour Local Board",
  "Lucas Heights": "Upper Harbour Local Board",

  "Birkenhead": "Kaipātiki Local Board",
  "Beach Haven": "Kaipātiki Local Board",
  "Birkdale": "Kaipātiki Local Board",
  "Chatswood": "Kaipātiki Local Board",
  "Glenfield": "Kaipātiki Local Board",
  "Hillcrest": "Kaipātiki Local Board",
  "Northcote": "Kaipātiki Local Board",
  "Northcote Point": "Kaipātiki Local Board",
  "Bayview": "Kaipātiki Local Board",
  "Totara Vale": "Kaipātiki Local Board",
  "Wairau Valley": "Kaipātiki Local Board",
  "Marlborough": "Kaipātiki Local Board",

  "Browns Bay": "Hibiscus and Bays Local Board",
  "Torbay": "Hibiscus and Bays Local Board",
  "Long Bay": "Hibiscus and Bays Local Board",
  "Rothesay Bay": "Hibiscus and Bays Local Board",
  "Murrays Bay": "Hibiscus and Bays Local Board",
  "Mairangi Bay": "Hibiscus and Bays Local Board",
  "Windsor Park": "Hibiscus and Bays Local Board",
  "Pinehill": "Hibiscus and Bays Local Board",
  "Orewa": "Hibiscus and Bays Local Board",
  "Silverdale": "Hibiscus and Bays Local Board",
  "Whangaparaoa": "Hibiscus and Bays Local Board",
  "Stanmore Bay": "Hibiscus and Bays Local Board",
  "Army Bay": "Hibiscus and Bays Local Board",
  "Gulf Harbour": "Hibiscus and Bays Local Board",
  "Manly": "Hibiscus and Bays Local Board",
  "Red Beach": "Hibiscus and Bays Local Board",
  "Hatfields Beach": "Hibiscus and Bays Local Board",
  "Arkles Bay": "Hibiscus and Bays Local Board",
  "Okura": "Hibiscus and Bays Local Board",
  "Stillwater": "Hibiscus and Bays Local Board",

  "Henderson": "Henderson-Massey Local Board",
  "Te Atatū Peninsula": "Henderson-Massey Local Board",
  "Te Atatū South": "Henderson-Massey Local Board",
  "Glendene": "Henderson-Massey Local Board",
  "Glen Eden": "Henderson-Massey Local Board",
  "Massey": "Henderson-Massey Local Board",
  "Ranui": "Henderson-Massey Local Board",
  "Swanson": "Henderson-Massey Local Board",
  "Sunnyvale": "Henderson-Massey Local Board",
  "Lincoln": "Henderson-Massey Local Board",
  "Westgate": "Henderson-Massey Local Board",
  "Royal Heights": "Henderson-Massey Local Board",
  "McLaren Park": "Henderson-Massey Local Board",
  "Western Heights": "Henderson-Massey Local Board",

  "Waitākere": "Waitākere Ranges Local Board",
  "Titirangi": "Waitākere Ranges Local Board",
  "Laingholm": "Waitākere Ranges Local Board",
  "Konini": "Waitākere Ranges Local Board",
  "Oratia": "Waitākere Ranges Local Board",
  "Waiatarua": "Waitākere Ranges Local Board",
  "Piha": "Waitākere Ranges Local Board",
  "Karekare": "Waitākere Ranges Local Board",
  "Bethells Beach": "Waitākere Ranges Local Board",

  "New Lynn": "Whau Local Board",
  "Avondale": "Whau Local Board",
  "Blockhouse Bay": "Whau Local Board",
  "Green Bay": "Whau Local Board",
  "Kelston": "Whau Local Board",
  "Rosebank": "Whau Local Board",

  "Auckland CBD": "Waitematā Local Board",
  "Ponsonby": "Waitematā Local Board",
  "Freemans Bay": "Waitematā Local Board",
  "Grey Lynn": "Waitematā Local Board",
  "Herne Bay": "Waitematā Local Board",
  "Parnell": "Waitematā Local Board",
  "Newmarket": "Waitematā Local Board",
  "Grafton": "Waitematā Local Board",
  "Eden Terrace": "Waitematā Local Board",
  "Arch Hill": "Waitematā Local Board",
  "St Marys Bay": "Waitematā Local Board",
  "Westmere": "Waitematā Local Board",
  "City Centre": "Waitematā Local Board",
  "Wynyard Quarter": "Waitematā Local Board",
  "Viaduct Harbour": "Waitematā Local Board",
  "Britomart": "Waitematā Local Board",

  "Ōrākei": "Ōrākei Local Board",
  "Orakei": "Ōrākei Local Board",
  "Ellerslie": "Ōrākei Local Board",
  "Glendowie": "Ōrākei Local Board",
  "Kohimarama": "Ōrākei Local Board",
  "Meadowbank": "Ōrākei Local Board",
  "Mission Bay": "Ōrākei Local Board",
  "Remuera": "Ōrākei Local Board",
  "St Heliers": "Ōrākei Local Board",
  "St Johns": "Ōrākei Local Board",
  "Saint Johns": "Ōrākei Local Board",
  "Stonefields": "Ōrākei Local Board",

  "Māngere": "Māngere-Ōtāhuhu Local Board",
  "Mangere": "Māngere-Ōtāhuhu Local Board",
  "Māngere Bridge": "Māngere-Ōtāhuhu Local Board",
  "Māngere East": "Māngere-Ōtāhuhu Local Board",
  "Ōtāhuhu": "Māngere-Ōtāhuhu Local Board",
  "Otahuhu": "Māngere-Ōtāhuhu Local Board",
  "Favona": "Māngere-Ōtāhuhu Local Board",
  "Middlemore": "Māngere-Ōtāhuhu Local Board",
  "Mangere Central": "Māngere-Ōtāhuhu Local Board",
  "Harania": "Māngere-Ōtāhuhu Local Board",

  "Maungakiekie": "Maungakiekie-Tāmaki Local Board",
  "Glen Innes": "Maungakiekie-Tāmaki Local Board",
  "Onehunga": "Maungakiekie-Tāmaki Local Board",
  "Penrose": "Maungakiekie-Tāmaki Local Board",
  "Royal Oak": "Maungakiekie-Tāmaki Local Board",
  "Te Papapa": "Maungakiekie-Tāmaki Local Board",
  "Tāmaki": "Maungakiekie-Tāmaki Local Board",
  "Point England": "Maungakiekie-Tāmaki Local Board",
  "Panmure": "Maungakiekie-Tāmaki Local Board",
  "Mount Wellington": "Maungakiekie-Tāmaki Local Board",
  "Sylvia Park": "Maungakiekie-Tāmaki Local Board",
  "Waikaraka": "Maungakiekie-Tāmaki Local Board",
  "Oranga": "Maungakiekie-Tāmaki Local Board",

  "Puketāpapa": "Puketāpapa Local Board",
  "Mount Roskill": "Puketāpapa Local Board",
  "Hillsborough": "Puketāpapa Local Board",
  "Three Kings": "Puketāpapa Local Board",
  "Lynfield": "Puketāpapa Local Board",
  "Waikowhai": "Puketāpapa Local Board",
  "Wesley": "Puketāpapa Local Board",
  "Roskill South": "Puketāpapa Local Board",

  "Ōtara": "Ōtara-Papatoetoe Local Board",
  "Otara": "Ōtara-Papatoetoe Local Board",
  "Papatoetoe": "Ōtara-Papatoetoe Local Board",
  "East Tāmaki": "Ōtara-Papatoetoe Local Board",
  "Manukau": "Ōtara-Papatoetoe Local Board",
  "Fairfield": "Ōtara-Papatoetoe Local Board",
  "Fergusons": "Ōtara-Papatoetoe Local Board",
  "Hunters Corner": "Ōtara-Papatoetoe Local Board",
  "Flat Bush": "Ōtara-Papatoetoe Local Board",

  "Manurewa": "Manurewa Local Board",
  "Clendon Park": "Manurewa Local Board",
  "Homai": "Manurewa Local Board",
  "Randwick Park": "Manurewa Local Board",
  "Weymouth": "Manurewa Local Board",
  "Wiri": "Manurewa Local Board",
  "Alfriston": "Manurewa Local Board",
  "The Gardens": "Manurewa Local Board",
  "Leabank": "Manurewa Local Board",

  "Papakura": "Papakura Local Board",
  "Takanini": "Papakura Local Board",
  "Opaheke": "Papakura Local Board",
  "Karaka": "Papakura Local Board",
  "Red Hill": "Papakura Local Board",
  "Drury": "Papakura Local Board",
  "Hingaia": "Papakura Local Board",
  "Pahurehure": "Papakura Local Board",
  "Rosehill": "Papakura Local Board",

  "Franklin": "Franklin Local Board",
  "Pukekohe": "Franklin Local Board",
  "Waiuku": "Franklin Local Board",
  "Tuakau": "Franklin Local Board",
  "Pokeno": "Franklin Local Board",
  "Clarks Beach": "Franklin Local Board",
  "Bombay": "Franklin Local Board",
  "Paerata": "Franklin Local Board",
  "Patumahoe": "Franklin Local Board",
  "Buckland": "Franklin Local Board",
  "Kingseat": "Franklin Local Board",
  "Glenbrook": "Franklin Local Board",
  "Hunua": "Franklin Local Board",
  "Beachlands": "Franklin Local Board",
  "Maraetai": "Franklin Local Board",
  "Clevedon": "Franklin Local Board",

  "Howick": "Howick Local Board",
  "Pakuranga": "Howick Local Board",
  "Botany Downs": "Howick Local Board",
  "Bucklands Beach": "Howick Local Board",
  "East Tāmaki Heights": "Howick Local Board",
  "Farm Cove": "Howick Local Board",
  "Half Moon Bay": "Howick Local Board",
  "Highland Park": "Howick Local Board",
  "Mellons Bay": "Howick Local Board",
  "Dannemora": "Howick Local Board",
  "Sunnyhills": "Howick Local Board",
  "Cockle Bay": "Howick Local Board",
  "Shelly Park": "Howick Local Board",
  "Ormiston": "Howick Local Board",
  "Chapel Downs": "Howick Local Board",
  "Botany": "Howick Local Board",

  "Rodney": "Rodney Local Board",
  "Kumeu": "Rodney Local Board",
  "Huapai": "Rodney Local Board",
  "Warkworth": "Rodney Local Board",
  "Matakana": "Rodney Local Board",
  "Snells Beach": "Rodney Local Board",
  "Algies Bay": "Rodney Local Board",
  "Helensville": "Rodney Local Board",
  "Parakai": "Rodney Local Board",
  "Wellsford": "Rodney Local Board",
  "Wainui": "Rodney Local Board",
  "Dairy Flat": "Rodney Local Board",
  "Coatesville": "Rodney Local Board",
  "Riverhead": "Rodney Local Board",
  "Kaukapakapa": "Rodney Local Board",
  "Muriwai": "Rodney Local Board",

  "Waiheke Island": "Waiheke Local Board",
  "Oneroa": "Waiheke Local Board",
  "Ostend": "Waiheke Local Board",
  "Surfdale": "Waiheke Local Board",
  "Palm Beach": "Waiheke Local Board",
  "Onetangi": "Waiheke Local Board",

  "Great Barrier Island": "Aotea / Great Barrier Local Board",
  "Tryphena": "Aotea / Great Barrier Local Board",
  "Claris": "Aotea / Great Barrier Local Board",
  "Port Fitzroy": "Aotea / Great Barrier Local Board",
};

export const ALL_SUBURBS = Object.keys(SUBURB_TO_LOCAL_BOARD).sort();

export const ALL_LOCAL_BOARDS = Array.from(new Set(Object.values(SUBURB_TO_LOCAL_BOARD))).sort();

export function getLocalBoard(suburb: string): string | null {
  const direct = SUBURB_TO_LOCAL_BOARD[suburb];
  if (direct) return direct;

  const lower = suburb.toLowerCase();
  for (const [key, board] of Object.entries(SUBURB_TO_LOCAL_BOARD)) {
    if (key.toLowerCase() === lower) return board;
  }
  return null;
}

export function searchSuburbs(query: string): string[] {
  if (!query.trim()) return [];
  const lower = query.toLowerCase();
  return ALL_SUBURBS.filter(s => s.toLowerCase().includes(lower)).slice(0, 15);
}
